export { AuthService } from './providers/auth-service';
export { DataService } from './providers/data-service';
export { DeleteService } from './providers/delete-service';
export { InsertService } from './providers/insert-service';
export { QueryService } from './providers/query-service';
export { SiteService } from './providers/site-service';
export { StorageService } from './providers/storage-service';
export { UpdateService } from './providers/update-service';
export { NgProvModule } from './ng-prov.module';